# Generated by Django 5.1.4 on 2025-01-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user_management_user',
        ),
        migrations.AlterModelTable(
            name='log',
            table='user_management_log',
        ),
    ]
